### ISSUE TITLE
Autostart [source build] -  fail with AttributeError: 'StdoutProxy' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#4561]
**Describe the bug**
When using the [autostart script](https://docs.hummingbot.io/global-configs/strategy-autostart/#source-autostart) for source build specified in the documentation page. The script failed with the following error::

```python
Traceback (most recent call last):
  File "bin/hummingbot_quickstart.py", line 144, in <module>
    main()
  File "bin/hummingbot_quickstart.py", line 140, in main
    asyncio.get_event_loop().run_until_complete(quick_start(args))
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "bin/hummingbot_quickstart.py", line 119, in quick_start
    await safe_gather(*tasks)
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/client/hummingbot_application.py", line 214, in run
    await self.app.run()
  File "/home/hummingbot/hummingbot/client/ui/hummingbot_cli.py", line 72, in run
    self.app = Application(layout=self.layout, full_screen=True, key_bindings=self.bindings, style=load_style(),
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 265, in __init__
    self.output = output or session.output
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/current.py", line 65, in output
    self._output = create_output()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/output/defaults.py", line 38, in create_output
    if io.isatty():
AttributeError: 'StdoutProxy' object has no attribute 'isatty'
```

Note: script work when password is remove `bin/hummingbot_quickstart.py -f CONFIG_FILE_NAME`
**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):

1. Install and run Hummingbot via source
1. Connect your API key
1. Create a strategy and use the exchange with API key connected and confirmed
1. Exit instance
1. Run autostart script : `bin/hummingbot_quickstart.py -f CONFIG_FILE_NAME -p CONFIG_PASSWORD`
 
...

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/138637372-dc00e738-1725-45ad-a349-1cd8dbea26ce.png)

**Release version**
0.44.0
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rp2x3y) by [Unito](https://www.unito.io)

**Comment by albertobaselga** [comment]
Hi, I have the same issue. Is there any available workaround? @gbjk how did you solve it?
Thanks in advance.

**Comment by kontox** [comment]
Hi, I have the same issue, but it's working fine with version 0.43.1 so I'm using this one until this is solved.

**Comment by RC-13** [comment]
A temporary workaround is to remove the password argument from the script `bin/hummingbot_quickstart.py -f CONFIG_FILE_NAME`

**Comment by albertobaselga** [comment]
@RC-13 but that means that you have to enter the password manually every time you restart the bot, right? Is there any other workaround for the Autostart functionality to work?

**Comment by JeremyKono** [comment]
Hi, @albertobaselga that's correct. You need to enter the password manually everytime

**Comment by gpavlov2016** [comment]
Do you have plans to fix it?

**Comment by kryptopoo** [comment]
note that it also happens on docker at higher v0.43.1 versions

**Comment by bmolodan** [comment]
Hi, try to setup autostart by cli `$ ./bin/hummingbot_quickstart.py -p psswd -f conf.yml`
Have anyone faced with such error:
```
Traceback (most recent call last):
  File "./bin/hummingbot_quickstart.py", line 146, in <module>
    main()
  File "./bin/hummingbot_quickstart.py", line 142, in main
    asyncio.get_event_loop().run_until_complete(quick_start(args))
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./bin/hummingbot_quickstart.py", line 121, in quick_start
    await safe_gather(*tasks)
  File "/Users/julfy/Projects/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/Users/julfy/Projects/hummingbot/hummingbot/client/hummingbot_application.py", line 213, in run
    await self.app.run()
  File "/Users/julfy/Projects/hummingbot/hummingbot/client/ui/hummingbot_cli.py", line 91, in run
    await self.app.run_async()
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 816, in run_async
    return await _run_async2()
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 792, in _run_async2
    result = await _run_async()
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 728, in _run_async
    self._redraw()
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 552, in _redraw
    self.context.copy().run(run_in_context)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 535, in run_in_context
    self.renderer.render(self, self.layout)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/renderer.py", line 707, in render
    output.flush()
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/output/vt100.py", line 691, in flush
    out.write(data.encode(self.stdout.encoding or "utf-8", "replace"))
  File "/Users/julfy/Projects/hummingbot/hummingbot/client/ui/stdout_redirection.py", line 89, in write
    self._write(data)
  File "/Users/julfy/Projects/hummingbot/hummingbot/client/ui/stdout_redirection.py", line 70, in _write
    if '\n' in data:
TypeError: a bytes-like object is required, not 'str'
```

Think these errors could be linked

PS. master, source build

**Comment by filipmacek** [comment]
> Hi, try to setup autostart by cli `$ ./bin/hummingbot_quickstart.py -p psswd -f conf.yml` Have anyone faced with such error:
> 
> ```
> Traceback (most recent call last):
>   File "./bin/hummingbot_quickstart.py", line 146, in <module>
>     main()
>   File "./bin/hummingbot_quickstart.py", line 142, in main
>     asyncio.get_event_loop().run_until_complete(quick_start(args))
>   File "/opt/anaconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "./bin/hummingbot_quickstart.py", line 121, in quick_start
>     await safe_gather(*tasks)
>   File "/Users/julfy/Projects/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
>     return await asyncio.gather(*args, **kwargs)
>   File "/Users/julfy/Projects/hummingbot/hummingbot/client/hummingbot_application.py", line 213, in run
>     await self.app.run()
>   File "/Users/julfy/Projects/hummingbot/hummingbot/client/ui/hummingbot_cli.py", line 91, in run
>     await self.app.run_async()
>   File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 816, in run_async
>     return await _run_async2()
>   File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 792, in _run_async2
>     result = await _run_async()
>   File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 728, in _run_async
>     self._redraw()
>   File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 552, in _redraw
>     self.context.copy().run(run_in_context)
>   File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 535, in run_in_context
>     self.renderer.render(self, self.layout)
>   File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/renderer.py", line 707, in render
>     output.flush()
>   File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/output/vt100.py", line 691, in flush
>     out.write(data.encode(self.stdout.encoding or "utf-8", "replace"))
>   File "/Users/julfy/Projects/hummingbot/hummingbot/client/ui/stdout_redirection.py", line 89, in write
>     self._write(data)
>   File "/Users/julfy/Projects/hummingbot/hummingbot/client/ui/stdout_redirection.py", line 70, in _write
>     if '\n' in data:
> TypeError: a bytes-like object is required, not 'str'
> ```
> 
> Think these errors could be linked
> 
> PS. master, source build

Yes, me too. Currently debugging why is not working

**Comment by sepa85** [comment]
Same here with docker version on raspberry pi, ver 0.46

I've tried some workaround but I didn't found nothing better to put the password. In that case, however, the autostart is not very useful anymore.

**Comment by kitos9112** [comment]
This issue is quite limiting in the sense that you cannot orchestrate multiple instances autonomously without inputting the password yourself. I'll investigate these days to see if I can tweak the source code and make it to work without breaking something else!

**Comment by sepa85** [comment]
Thank you kitos.. Actually I'm using a downgraded version (0.43.1 arm beta) and it works, but I'll still think autostart is a nice features for some people, and with the need to insert the password, it is not useful anymore.

If you have a plan to re insert this feature in main branch, I'd appreciate it.

**Comment by sepa85** [comment]
Or maybe I'm missing some other best way to orchestrate different bots without restarting the docker. Are you using something different? Or it's just a not common needing?

Anyway, I'd really enjoy the 1.0.0 version now, but the autostart is still broken. Do you suggest some (even ugly) workaround to enjoy the new stable version without putting the password?

Thank you.. ;)

**Comment by ulrickpsp** [comment]
Hi folks. I've been suffering this issue for some time. Has anybody been able to find a temporary workaround?

**Comment by rapcmia** [comment]
The fix for autostart has been deployed on the next Hummingbot 1.2.0 release and working ok on development branch as well. Closing ticket for now
![ubuntu1804_EFBbRU58no](https://user-images.githubusercontent.com/73840223/161021452-0db44cdf-5062-490a-9f96-977b74f2bef4.gif)
