### ISSUE TITLE
Fixed Grid strategy, market can not be configured.

### ISSUE THREAD

**Issue by ZeroCool940711** [hummingbot/hummingbot#5453]
**Describe the bug**
When creating a new config for the new fixed grid strategy when it asks for the market to trade in it throws an error and it does not progress to the next step.

**Steps To Reproduce**
1- Open Hummingbot.
2- Use the `create` command to create a new config.
3- Select `fixed_grid` from the list of strategies.
4- Try to enter the market spot connector where you want to try, for example Kucoin.
5- HummingBot will get stuck and will not be able to progress to the next step and ask forever for the market spot connector.

**Screenshots**
![image](https://user-images.githubusercontent.com/5977640/176911787-62a8fd06-cff4-459a-b1b7-728b0b1d64f0.png)

**Logs**
```
2022-07-01 13:51:36,809 - 382258 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'set' object has no attribute 'append'
Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/hummingbot/hummingbot/client/command/create_command.py", line 65, in prompt_for_configuration
    file_name = await self.prompt_for_configuration_legacy(file_name, strategy, config_map)
  File "/home/ubuntu/hummingbot/hummingbot/client/command/create_command.py", line 124, in prompt_for_configuration_legacy
    await self.prompt_a_config_legacy(config)
  File "/home/ubuntu/hummingbot/hummingbot/client/command/create_command.py", line 201, in prompt_a_config_legacy
    err_msg = await config.validate(input_value)
  File "/home/ubuntu/hummingbot/hummingbot/client/config/config_var.py", line 84, in validate
    self._on_validated(value)
  File "/home/ubuntu/hummingbot/hummingbot/strategy/fixed_grid/fixed_grid_config_map.py", line 44, in exchange_on_validated
    required_exchanges.append(value)
AttributeError: 'set' object has no attribute 'append'
```

**HummingBot Version**
Hummingbot is running from source using the latest code from the development branch.

**Optional: your discord username: *Tukirito#1748*

**Comment by david-hummingbot** [comment]
was able to replicate this issue on dev-1.6.0, it's working on the master branch though - 1.5.0

![2022-07-01_234546](https://user-images.githubusercontent.com/85695272/176928006-190e7642-756a-4aaf-babc-32ca47b5d2a1.jpg)

**Comment by abduramann** [comment]
I use binance as a connector for the fixed grid and there is no problem. FYI.

**Comment by JeremyKono** [comment]
Hi @rkc2000, there seems to be an issue with your strategy. Can you please come to take a look and push a fix if you can? Thanks!

**Comment by cardosofede** [comment]
@ZeroCool940711 check the modification of @rkc2000 and let us know if this solves your issue

**Comment by rapcmia** [comment]
Fix has been already deployed to latest hummingbot version
