### PR TITLE
Feat/add db migration

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Since we are adding a new column in the trade fees table, this PR makes the migration from the older structure of the database automatic for the user.

QA:
- Run a bot with the old version
- Update the bot to the last version and see if there is not an error in the migration

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update: 
- Tested on local WSL Ubuntu20.04, created docker image for this PR successfully 🆗 
- Create a simple PMM paper on latest docker
- After getting filled, check CSV and removed cointainer
- Pull PR docker image and import then start the strategy
  image
  - Confirm `Will run DB migration from 20220130 to 20230516`
  - Confirm `Applying AddTradeFeeInQuote to DB...`
  - However getting `Unhandled error in background task: **init**() missing 1 required positional argument: 'scale'`
    ```
    2023-05-18 05:19:16,504 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: __init__() missing 1 required positional argument: 'scale'
    Traceback (most recent call last):
      File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
        return await c
      File "/home/hummingbot/hummingbot/client/command/import_command.py", line 55, in import_config_file
        self.strategy_file_name = file_name
      File "/home/hummingbot/hummingbot/client/hummingbot_application.py", line 147, in strategy_file_name
        self.trade_fill_db = SQLConnectionManager.get_trade_fills_instance(
      File "/home/hummingbot/hummingbot/model/sql_connection_manager.py", line 47, in get_trade_fills_instance
        cls._scm_trade_fills_instance = SQLConnectionManager(
      File "/home/hummingbot/hummingbot/model/sql_connection_manager.py", line 97, in __init__
        self.check_and_migrate_db(client_config_map)
      File "/home/hummingbot/hummingbot/model/sql_connection_manager.py", line 126, in check_and_migrate_db
        was_migration_successful = Migrator().migrate_db_to_version(
      File "/home/hummingbot/hummingbot/model/db_migration/migrator.py", line 49, in migrate_db_to_version
        new_db_handle = transformation.apply(new_db_handle)
      File "/home/hummingbot/hummingbot/model/db_migration/transformations.py", line 141, in apply
        trade_fee = Column("trade_fee_in_quote", SqliteDecimal, nullable=True)
      File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 1695, in __init__
        super(Column, self).__init__(name, type_)
      File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 4924, in __init__
        self.type = type_api.to_instance(type_)
      File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/sql/type_api.py", line 1957, in to_instance
        return typeobj(*arg, **kw)
    TypeError: __init__() missing 1 required positional argument: 'scale'
    ```

Steps to reproduce:
1. Create a docker client build on latest version 1.15.0
2. Create simple PMM and wait for order fills 
3. After getting order fill, check CSV then exit the client. Remove the container `docker rm <container name>`
4. Pull PR docker client image. Import and start the strategy
5. Observe behavior

Attached logs:
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/11504666/logs_hummingbot.log)

**Comment by cardosofede** [comment]
@rapcmia can you test this from source?

**Comment by rapcmia** [comment]
> @rapcmia can you test this from source?

Setup with fork repo's development branch on source then checkout this branch and still getting the `Unhandled error in background task: (sqlite3.OperationalError)`

image

```
2023-05-24 14:17:34,322 - 19961 - root - INFO - Will run DB migration from 20220130 to 20230516
2023-05-24 14:17:34,322 - 19961 - root - INFO - Applying AddTradeFeeInQuote to DB...
2023-05-24 14:17:34,339 - 19961 - root - INFO - DONE with AddTradeFeeInQuote
2023-05-24 14:17:34,341 - 19961 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: UPDATE "Metadata" SET value=? WHERE "Metadata"."key" = ?]
[parameters: ('20230516', 'local_db_version')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rapcmia/github/hummingbot/6304/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/rapcmia/github/hummingbot/6304/hummingbot/client/command/import_command.py", line 55, in import_config_file
    self.strategy_file_name = file_name
  File "/home/rapcmia/github/hummingbot/6304/hummingbot/client/hummingbot_application.py", line 147, in strategy_file_name
    self.trade_fill_db = SQLConnectionManager.get_trade_fills_instance(
  File "/home/rapcmia/github/hummingbot/6304/hummingbot/model/sql_connection_manager.py", line 47, in get_trade_fills_instance
    cls._scm_trade_fills_instance = SQLConnectionManager(
  File "/home/rapcmia/github/hummingbot/6304/hummingbot/model/sql_connection_manager.py", line 97, in __init__
    self.check_and_migrate_db(client_config_map)
  File "/home/rapcmia/github/hummingbot/6304/hummingbot/model/sql_connection_manager.py", line 132, in check_and_migrate_db
    self.get_local_db_version(session=session).value = self.LOCAL_DB_VERSION_VALUE
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/util.py", line 237, in __exit__
    self.rollback()
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/util.py", line 233, in __exit__
    self.commit()
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3444, in flush
    self._flush(objects)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3584, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3544, in _flush
    flush_context.execute()
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 237, in save_obj
    _emit_update_statements(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1001, in _emit_update_statements
    c = connection._execute_20(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: UPDATE "Metadata" SET value=? WHERE "Metadata"."key" = ?]
[parameters: ('20230516', 'local_db_version')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

Steps to reproduce:
- Setup latest branch on forked repo
- Setup simple pmm on paper and check CSV and all are expected ✅
- Checkout this PR and recompile
- Observe behavior

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/11551121/logs_hummingbot.log)

**Comment by rapcmia** [comment]
PR update:
- Initially checkout `82b1b47a0901ed8299c7176edaf21a9d6f49ef29 for v1.15.0`
    - Setup PMM papertrade and confirm CSV files are available with trade data
    - Change permission to `chmod 777`
- Checkout PR branch `feat/add_db_migration`
    - Change permission of folders to `chmod 777`
    - Start the client and import the strategy file but getting `nexpected error while checking and upgrading the local database`
      image
      ```
      2023-06-06 13:56:25,041 - 22197 - root - INFO - Will run DB migration from 20220130 to 20230516
      2023-06-06 13:56:25,041 - 22197 - root - INFO - Applying AddTradeFeeInQuote to DB...
      2023-06-06 13:56:25,042 - 22197 - root - ERROR - Unexpected error while checking and upgrading the local database.
      Traceback (most recent call last):
        File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
          self.dialect.do_execute(
        File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
          cursor.execute(statement, parameters)
      sqlite3.OperationalError: duplicate column name: trade_fee_in_quote
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/home/rapcmia/github/hummingbot/6304/hummingbot/model/db_migration/migrator.py", line 49, in migrate_db_to_version
          new_db_handle = transformation.apply(new_db_handle)
        File "/home/rapcmia/github/hummingbot/6304/hummingbot/model/db_migration/transformations.py", line 142, in apply
          self.add_column(db_handle.engine, "TradeFill", trade_fee, dry_run=False)
        File "/home/rapcmia/github/hummingbot/6304/hummingbot/model/db_migration/base_transformation.py", line 57, in add_column
          engine.execute(query_to_execute)
        File "<string>", line 2, in execute
        File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 468, in warned
          return fn(*args, **kwargs)
        File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3257, in execute
          return connection.execute(statement, *multiparams, **params)
        File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1365, in execute
          return self._exec_driver_sql(
        File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1669, in _exec_driver_sql
          ret = self._execute_context(
        File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
          self._handle_dbapi_exception(
        File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
          util.raise_(
        File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
          raise exception
        File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
          self.dialect.do_execute(
        File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
          cursor.execute(statement, parameters)
      sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) duplicate column name: trade_fee_in_quote
      [SQL: ALTER TABLE "TradeFill" ADD COLUMN trade_fee_in_quote BIGINT NULL]
      (Background on this error at: https://sqlalche.me/e/14/e3q8)
      ```

Steps to produce:
1. Checkout v1.15 and setup simple PMM until there is a filled order
2. Check if the order are recorded successfully on data folder then change folder/file permission
3. Checkout to this PR branch and import again, getting previous error about `...readonly database` so exit the client and change permission again to` sudo chmod 777 data/*`
4. Open then import the strategy file again, observe the error message

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/11660756/logs_hummingbot.log)
